name: 🔐 Security Audit Composite Action
description: Run security audits for different package managers

inputs:
  audit-type:
    description: 'Type of audit to run (npm-audit or pip-audit)'
    required: true
  working-directory:
    description: 'Directory to run the audit in'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js for npm audit
      if: inputs.audit-type == 'npm-audit'
      uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: ${{ inputs.working-directory }}/package-lock.json

    - name: Install dependencies for npm audit
      if: inputs.audit-type == 'npm-audit'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: npm ci

    - name: Run npm audit
      if: inputs.audit-type == 'npm-audit'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "Running npm audit..."
        npm audit --audit-level=moderate || {
          echo "⚠️ npm audit found vulnerabilities"
          echo "Check the security tab for details"
          exit 1
        }

    - name: Setup Python for pip audit
      if: inputs.audit-type == 'pip-audit'
      uses: actions/setup-python@0b93645e9fea7318ecaad2b719ef409de67e9809 # v5.3.0
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install pip-audit
      if: inputs.audit-type == 'pip-audit'
      shell: bash
      run: pip install pip-audit

    - name: Run pip audit
      if: inputs.audit-type == 'pip-audit'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "Running pip audit..."
        pip-audit --desc --format=json --output=audit-results.json || {
          echo "⚠️ pip audit found vulnerabilities"
          echo "Check audit-results.json for details"
          exit 1
        }