name: 🧪 Test Composite Action

description: 'Composite action for running tests with consistent configuration'

inputs:
  test-type:
    description: 'Type of test to run (frontend-lint, frontend-test, python-compile, python-test)'
    required: true
  working-directory:
    description: 'Working directory for the tests'
    required: false
    default: '.'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Setup Node.js (if frontend test)
      if: contains(inputs.test-type, 'frontend')
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: npm
        cache-dependency-path: frontend/package-lock.json

    - name: Setup Python (if python test)
      if: contains(inputs.test-type, 'python')
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: "pip"
        cache-dependency-path: bot/requirements.txt

    - name: Install frontend dependencies
      if: contains(inputs.test-type, 'frontend')
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        npm ci
        npx prisma generate

    - name: Install Python dependencies
      if: contains(inputs.test-type, 'python')
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt pytest

    - name: Run lint
      if: inputs.test-type == 'frontend-lint'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: npm run lint

    - name: Run frontend tests
      if: inputs.test-type == 'frontend-test'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: npm run test:server-settings --if-present

    - name: Byte-compile Python sources
      if: inputs.test-type == 'python-compile'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: python -m compileall src

    - name: Run pytest
      if: inputs.test-type == 'python-test'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: pytest -q